'use client'
import { NavContextProvider } from "@/context/NavContext";
import { Content, Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import Navbar from "@/components/Navbar"
import Header from "@/components/Header"
import { createContext, useState } from "react";

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Classizz",
//   description: "Generated by create next app",
// };


const RootLayout = ({
  children,
}) => {
  const login = true;
  return (
    <html lang="en">
      <body className={inter.className}>
        <NavContextProvider>
          <div className="flex w-screen">
            {
              login &&
              <div className="w-72 ">
                <Navbar />
              </div>
            }

            <div className="w-full flex flex-col max-h-screen">
              <Header />

              {children}
            </div>
          </div>
        </NavContextProvider>
        <Toaster />
      </body>
    </html>
  );
}

export default RootLayout